version: '3.1'

services:

  db:
    container_name: postgres-demo
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"